### ISSUE TITLE
Package name is deceptive

### ISSUE THREAD

**Issue by AffectedArc07** [zlstringham/libbyond#1]
`libbyond.so` is already the name of a library that is part of BYOND (basically linux's version of `byondcore.dll`)

![image](https://user-images.githubusercontent.com/25063394/160110765-85898956-f46c-465b-ace8-199ad8ee788c.png)

May want to clarify it in the readme

**Comment by zlstringham** [comment]
Will clarify in readme, but to be fair this is a compilation of libraries so it wouldn't compile to an actual "libbyond.*" but perhaps "libbyondcrc32.*" etc
